module.exports = {
  School: require('./School'),
  PlatformAdmin: require('./PlatformAdmin'),
  SchoolSettings: require('./SchoolSettings'),
  User: require('./User'),
  Teacher: require('./Teacher'),
  AcademicYear: require('./AcademicYear'),
  Class: require('./Class'),
  Section: require('./Section'),
  Subject: require('./Subject'),
  Student: require('./Student'),
  Enrollment: require('./Enrollment'),
  TeacherAssignment: require('./TeacherAssignment'),
  TeacherAttendanceScope: require('./TeacherAttendanceScope'),
  Exam: require('./Exam'),
  StudentExamResult: require('./StudentExamResult'),
  Room: require('./Room'),
  RoomAssignment: require('./RoomAssignment'),
  PromotionRecommendation: require('./PromotionRecommendation'),
  Announcement: require('./Announcement'),
  StudentTransfer: require('./StudentTransfer'),
  Attendance: require('./Attendance'),
  TeacherAttendance: require('./TeacherAttendance'),
  Fee: require('./Fee'),
  Homework: require('./Homework'),
  Assignment: require('./Assignment'),
  Counter: require('./Counter'),
}
